"""Reference design miner: multi-page landing via injected `base_design` SDK.

Uses `task` / `llm.chat` / `out.write_page` only. Operator injects the SDK;
this file is what miners submit (plus `pyproject.toml`).
"""

from __future__ import annotations

import html
import re

PAGES: tuple[tuple[str, str], ...] = (
    ("index.html", "hero landing with value proposition and primary CTA"),
    ("pricing.html", "three pricing tiers with feature comparison"),
    ("components.html", "showcase of reusable UI components (cards, badges, tables)"),
)

SYSTEM = """You are a senior product designer writing production static HTML.
Return ONLY one complete HTML5 document — no markdown fences, no commentary.
Rules:
- semantic HTML5 + a single <style> block in <head>
- no <script>, no iframes, no forms that POST, no external stylesheets
- distinctive, finished visual design matching the product brief
- include data-agent="design-baseline" on <html>
- page must be self-contained and readable without JS
"""


def _extract_html(text: str) -> str:
    t = (text or "").strip()
    if not t:
        return ""
    if t.startswith("```"):
        t = re.sub(r"^```(?:html)?\s*", "", t, flags=re.IGNORECASE)
        t = re.sub(r"\s*```$", "", t)
    return t.strip()


def _looks_like_html(text: str) -> bool:
    low = text.lower()
    return "<html" in low and "</html>" in low and "<body" in low


def _fallback(page: str, prompt: str) -> str:
    """Deterministic multi-page HTML when the LLM is unavailable or returns junk."""
    title = {
        "index.html": "Home",
        "pricing.html": "Pricing",
        "components.html": "Components",
    }.get(page, page)
    safe_prompt = html.escape(prompt.strip() or "Product landing")
    nav = """
    <nav class="nav">
      <a href="index.html">Home</a>
      <a href="pricing.html">Pricing</a>
      <a href="components.html">Components</a>
    </nav>"""
    if page == "pricing.html":
        body = f"""
        <header class="hero"><h1>Pricing</h1><p>{safe_prompt}</p></header>
        {nav}
        <main class="grid">
          <section class="card"><h2>Starter</h2><p class="price">$29</p><ul><li>Core analytics</li><li>Email support</li></ul></section>
          <section class="card featured"><h2>Growth</h2><p class="price">$99</p><ul><li>Everything in Starter</li><li>SSO</li><li>Priority support</li></ul></section>
          <section class="card"><h2>Enterprise</h2><p class="price">Custom</p><ul><li>Dedicated CSM</li><li>SLA</li></ul></section>
        </main>"""
    elif page == "components.html":
        body = f"""
        <header class="hero"><h1>Components</h1><p>{safe_prompt}</p></header>
        {nav}
        <main>
          <section class="card"><h2>Metric card</h2><p class="stat">98.2%</p><p>Uptime this quarter</p></section>
          <section class="card"><h2>Badge row</h2><p><span class="badge">New</span> <span class="badge alt">Beta</span></p></section>
          <section class="card"><h2>Data table</h2>
            <table><thead><tr><th>Name</th><th>Status</th></tr></thead>
            <tbody><tr><td>Ingest</td><td>Healthy</td></tr><tr><td>Warehouse</td><td>Healthy</td></tr></tbody></table>
          </section>
        </main>"""
    else:
        body = f"""
        <header class="hero">
          <p class="eyebrow">design-baseline</p>
          <h1>{safe_prompt}</h1>
          <p class="lede">Ship a clear story across home, pricing, and components — generated by the reference miner harness.</p>
          <p><a class="cta" href="pricing.html">See pricing</a></p>
        </header>
        {nav}
        <main class="grid">
          <section class="card"><h2>Clarity</h2><p>One job per page, strong hierarchy.</p></section>
          <section class="card"><h2>Trust</h2><p>Concrete proof points and calm typography.</p></section>
          <section class="card"><h2>Action</h2><p>Obvious next step toward conversion.</p></section>
        </main>"""
    return f"""<!DOCTYPE html>
<html lang="en" data-agent="design-baseline" data-page="{html.escape(page)}">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{html.escape(title)} · Baseline</title>
  <style>
    :root {{
      --bg: #0f1419; --fg: #f4f1ea; --muted: #b7b1a3; --accent: #3dd6c6;
      --card: #1a222c; --line: #2a3441; --font: "Iowan Old Style", "Palatino Linotype", Palatino, serif;
      --sans: "Avenir Next", "Segoe UI", sans-serif;
    }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; font-family: var(--sans); color: var(--fg); background:
      radial-gradient(1200px 600px at 10% -10%, #1d3a3a 0%, transparent 55%),
      linear-gradient(180deg, #101820, var(--bg)); min-height: 100vh; }}
    .hero {{ padding: 4.5rem 1.5rem 2rem; max-width: 920px; margin: 0 auto; }}
    .eyebrow {{ letter-spacing: 0.14em; text-transform: uppercase; color: var(--accent); font-size: 0.75rem; }}
    h1 {{ font-family: var(--font); font-size: clamp(2.2rem, 5vw, 3.6rem); line-height: 1.05; margin: 0.4rem 0 1rem; }}
    .lede {{ color: var(--muted); font-size: 1.15rem; max-width: 40rem; }}
    .cta {{ display: inline-block; margin-top: 1rem; background: var(--accent); color: #062822; padding: 0.8rem 1.2rem;
      text-decoration: none; font-weight: 700; border-radius: 4px; }}
    .nav {{ display: flex; gap: 1rem; padding: 0.75rem 1.5rem; border-top: 1px solid var(--line);
      border-bottom: 1px solid var(--line); position: sticky; top: 0; background: rgba(15,20,25,0.92); }}
    .nav a {{ color: var(--fg); text-decoration: none; }}
    main {{ max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem 4rem; }}
    .grid {{ display: grid; gap: 1rem; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); }}
    .card {{ background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 1.25rem; }}
    .card.featured {{ outline: 2px solid var(--accent); }}
    .price {{ font-size: 2rem; margin: 0.4rem 0; color: var(--accent); }}
    .badge {{ display: inline-block; padding: 0.2rem 0.55rem; border-radius: 999px; background: #244; color: var(--accent); font-size: 0.8rem; }}
    .badge.alt {{ background: #332a18; color: #e6c07b; }}
    .stat {{ font-size: 2.4rem; margin: 0; font-family: var(--font); }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ text-align: left; padding: 0.55rem 0.4rem; border-bottom: 1px solid var(--line); }}
  </style>
</head>
<body>
{body}
</body>
</html>
"""


def run(task, llm, out) -> None:
    prompt = getattr(task, "prompt", "") or ""
    for page, focus in PAGES:
        messages = [
            {"role": "system", "content": SYSTEM},
            {
                "role": "user",
                "content": (
                    f"Product brief:\n{prompt}\n\n"
                    f"Build the page file `{page}` focused on: {focus}.\n"
                    f"Required pages for this run: {getattr(task, 'pages_required', [])}."
                ),
            },
        ]
        html_doc = ""
        try:
            raw = llm.chat(messages)
            html_doc = _extract_html(raw)
        except Exception:
            html_doc = ""
        if not _looks_like_html(html_doc):
            html_doc = _fallback(page, prompt)
        # Ensure attribution marker survives LLM output without scripts.
        if 'data-agent="design-baseline"' not in html_doc:
            html_doc = html_doc.replace("<html", '<html data-agent="design-baseline"', 1)
        out.write_page(page, html_doc)
